# -------------------------------
# spring app local configuration
# -------------------------------
spring:
  main:
    web-application-type: none
  profiles: local
  messages:
    cache-duration: -1
  resources:
    # キャッシュの無効化
    cache:
      period: 0
  # -------------
  # datasource
  # -------------
  datasource:
    url: jdbc:postgresql://localhost:5432/apex_vis
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
    
logging:
  level:
    root: INFO
    org.springframework: WARN
    jp.co.acms.web : DEBUG
  file: logs/spring-boot-logging.log
