debug: true
spring:
  profiles:
    default: local
    active: local
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    mode: HTML
  resources:
    # 静的コンテンツをキャッシュする
    cache:
      period: 604800
    chain:
      # GZipされているリソースがあれば使う
      compressed: true
      strategy:
        content:
          # コンテンツのMD5ハッシュ値によるバージョニング
          enabled: true
          paths: /**   

#logging:
#  file: ${SPF_LOGGING_PATH:app-logs/}log-@project.artifactId@-app.log
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"

# ----------------------
# Server configuration
# ----------------------
server:
  port: 8080
  compression:
    enabled: true
  servlet:
    session:
      timeout: 7200
      # URLにセッションIDを出力しないようにする
#      tracking-modes: cookie
    context-path: /
    
# -----------------------
# MyBatis configuration
# -----------------------
mybatis:
  mapper-locations: classpath:mybatis-mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
    shrink-whitespaces-in-sql: true
    
---
spring:
  profiles: test
---
spring:
  profiles: production